### ISSUE TITLE
Openshift start error, conf not found

### ISSUE THREAD

**Issue by duchymor** [sburn/docker-apache-atlas#12]
Once deployed in Openshift it won't run. The error is quite straightforward, but I have no idea why the file is not in place.
Thanks for any hint.

```
Exception: [Errno 2] No such file or directory: '/opt/apache-atlas-2.1.0/conf/atlas-application.properties' 

Traceback (most recent call last):
  File "/opt/apache-atlas-2.1.0/bin/atlas_start.py", line 191, in <module>
    returncode = main()
  File "/opt/apache-atlas-2.1.0/bin/atlas_start.py", line 84, in main
    is_hbase = mc.is_hbase(confdir)
  File "/opt/apache-atlas-2.1.0/bin/atlas_config.py", line 411, in is_hbase
    storageBackEnd = getConfig(confFile, STORAGE_BACKEND_CONF)
  File "/opt/apache-atlas-2.1.0/bin/atlas_config.py", line 689, in getConfig
    for line in open(file).readlines():
IOError: [Errno 2] No such file or directory: '/opt/apache-atlas-2.1.0/conf/atlas-application.properties'
```

**Comment by sburn** [comment]
Have you built it from Dockerfile with Openshift or used a ready image from Docker Hub?

**Comment by duchymor** [comment]
It's built in gitlab first, from dockerfile: 
```
FROM sburn/apache-atlas
ENTRYPOINT /opt/apache-atlas-2.1.0/bin/atlas_start.py
```
