### ISSUE TITLE
Error "No such file or directory" when starting Atlas with configuration volumes exposed

### ISSUE THREAD

**Issue by kell18** [sburn/docker-apache-atlas#13]
Hi!

One example from docs:
```
docker run --detach \
    -v ${PWD}/pre-conf:/opt/apache-atlas-2.1.0/conf \
    -p 21000:21000 \
    --name atlas \
    sburn/apache-atlas \
    /opt/apache-atlas-2.1.0/bin/atlas_start.py
```

Is not working due to:
```
Exception: [Errno 2] No such file or directory: '/opt/apache-atlas-2.1.0/conf/atlas-application.properties'
Traceback (most recent call last):
  File "/opt/apache-atlas-2.1.0/bin/atlas_start.py", line 191, in <module>
    returncode = main()
  File "/opt/apache-atlas-2.1.0/bin/atlas_start.py", line 84, in main
    is_hbase = mc.is_hbase(confdir)
  File "/opt/apache-atlas-2.1.0/bin/atlas_config.py", line 411, in is_hbase
    storageBackEnd = getConfig(confFile, STORAGE_BACKEND_CONF)
  File "/opt/apache-atlas-2.1.0/bin/atlas_config.py", line 689, in getConfig
    for line in open(file).readlines():
IOError: [Errno 2] No such file or directory: '/opt/apache-atlas-2.1.0/conf/atlas-application.properties'
```

But if you run the container without configs exposed - file `atlas-application.properties` could be found in `/opt/apache-atlas-2.1.0/conf`. Not sure why it's happening.

**Comment by kell18** [comment]
I guess I see now, the problem is that I mount my host volumes in the container, which overrides everything there so leaving empty config folder there. Thanks anyway! I'll close the issue then.
